### ISSUE TITLE
tests are broken

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/basicrta#8]
## Expected behavior ##

Tests run.

## Actual behavior ##

No tests are running. Failure
```

Run python -m pytest
ImportError while loading conftest '/home/runner/work/basicrta/basicrta/basicrta/tests/conftest.py'.
basicrta/__init__.py:9: in <module>
    __version__ = version("basicrta")
E   importlib.metadata.PackageNotFoundError: basicrta
```

**Comment by orbeckst** [comment]
Check a recent cookiecutter gh-ci.yaml file such as https://github.com/MDAnalysis/helanal/blob/main/.github/workflows/gh-ci.yaml and update yours accordingly. There may have been changes in the workflow since you generated yours and unfortunately there's no automated way to update with the cookiecutter (at least as far as I am aware).


You shouldn't need python-package.yaml (delete) unless you want to write a workflow from scratch.

**Comment by orbeckst** [comment]
Or look at https://github.com/MDAnalysis/PathSimAnalysis/blob/main/.github/workflows/gh-ci.yaml --- Irfan recently updated something in there, and it was originally created with a fairly old version of the MDA cookiecutter.

(The PathSimAnalysis repo also has a nice deploy.yaml workflow that automatically uploads tagged commits to testpypi and releases to pypi.)

**Comment by orbeckst** [comment]
You can also look at the current version of the *template* for the gh-ci.yaml file in the mda-cookiecutter repo https://github.com/MDAnalysis/cookiecutter-mdakit/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/.github/workflows/%7B%7Bcookiecutter._ci_name%7D%7D.yaml (just be careful because it contains template strings).

**Comment by rsexton2** [comment]
Tests are failing for "windows-latest", which is because MDAnalysis is not found.
Tests also fail for development version of MDAnalysis, checking into that.
Ubuntu and MacOS tests pass for latest mda version

**Comment by orbeckst** [comment]
I opened #10 for the specific windows issue and will close this one because Linux and macOS is passing.
